// <auto-generated />
namespace VeterinariaFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class actualizacion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(actualizacion));
        
        string IMigrationMetadata.Id
        {
            get { return "202305082025144_actualizacion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
